hytech-racing/circuits-support-2022

CAM Files/2 Layer/Docu (2 Layer).cam, CAM Files/2 Layer/Name Docu (2 Layer).cam, CAM Files/2 Layer/Name Value Docu (2 Layer).cam, CAM Files/4 Layer/Docu (4 Layer).cam, CAM Files/4 Layer/Name Docu (4 Layer).cam, CAM Files/4 Layer/Name Value Docu (4 Layer).cam, CAM Files/6 Layer/Docu (6 Layer).cam, CAM Files/6 Layer/Name Docu (6 Layer).cam, CAM Files/6 Layer/Name Value Docu (6 Layer).cam
CAM files were accidentally deleted transitioning to 2022 repo
=> Re added cam files

EAGLE Libraries/HyTechDevices.lbr, EAGLE Libraries/HyTechSupplies.lbr
Added 330k, 2k, 30k, 15k, 1.33k, and 73.2k Panasonic Electric Components resisters. Added a green LED.
=> Efuse+ams parts

EAGLE Libraries/HyTechDevices.lbr
Added a Panasonic Electronic Company 255 kOhm resistor.
=> Added 255 kOhm Resistor

EAGLE Libraries/HyTechDevices.lbr, EAGLE Libraries/HyTechSupplies.lbr
Made AVR ISP connector mirrored peripheral and added fused and unfused ts connectors
*All datasheets, information, and/or useful links should be included in the Description within EAGLE.*
- - [] Did you *make a PR* for them in `circuits-2022`? If so, please pause until you get this PR merged.
- - [x] Did you *check for merge conflicts*?
- - [x] Did you *resolve* any that occurred? ***If you are having trouble or are confused, contact a lead!***
=> Minor fixes

EAGLE Libraries/HyTechDevices.lbr
=> moved ground pin to better fit cap

.gitignore, ULP Files/cmd-renumber.ulp, ULP Files/trace-bmp.ulp
=> Added Nathan Cheek ULPs

EAGLE Libraries/HyTechDevices.lbr, EAGLE Libraries/HyTechSupplies.lbr
=> Fixed Yageo links

EAGLE Libraries/HyTechDevices.lbr
=> changed vreg out to supply

EAGLE Libraries/HyTechDevices.lbr
=> Added attributes for ordering

EAGLE Libraries/HyTechDevices.lbr
3.32k and 8.66k 0603 res
*All datasheets, information, and/or useful links should be included in the Description within EAGLE.*
=> Added 3.32k and 8.66k 0603 res

EAGLE Libraries/HyTechDevices.lbr
=> Ams rev 17

EAGLE Libraries/HyTechDevices.lbr
=> Minor layer fixes

EAGLE Libraries/HyTechDevices.lbr, EAGLE Libraries/HyTechManufacturing.lbr
=> Fiducial changes

EAGLE Libraries/HyTechManufacturing.lbr
=> Made fiducial only on one layer

EAGLE Libraries/HyTechDevices.lbr
Added 10-pin AVR connector assignments and fixed 6-pin swapped SDI and SDO
- [ x] Did you pull `main` into your branch?
- - [x ] Did you *check for merge conflicts*?
- - [x ] Did you *resolve* any that occurred? ***If you are having trouble or are confused, contact a lead!***
- [x ] Did you fill out the above template?
- [x ] Did you assign the right people for review (on the right)?
- [x ] Did you comply with the library style guidelines?
=> Fixed SDI/SDO for AVR Connectors

EAGLE Libraries/HyTechDevices.lbr
Rejected dashboard PR and updated SPI lines for ATMEGA and ISP header to be consistent with new standards
=> Spi dash fix

EAGLE Libraries/HyTechDevicesTemp.lbr
=> Adafruit Ultimate GPS

EAGLE Libraries/HyTechDevices.lbr, EAGLE Libraries/HyTechExternal.lbr
=> Gps fix fix fix

EAGLE Libraries/HyTechExternal.lbr
=> Added microfit receptacles

EAGLE Libraries/HyTechDevices.lbr
=> RA microfits

EAGLE Libraries/HyTechDevices.lbr, EAGLE Libraries/HyTechExternal.lbr
=> Minor improvements

EAGLE Libraries/HyTechDevices.lbr, EAGLE Libraries/HyTechSupplies.lbr
=> Thermal fix

EAGLE Libraries/HyTechDevices.lbr, ULP Files/rename-testpoints.ulp
=> Unholy ULP Patch

EAGLE Libraries/HyTechDevices.lbr
=> 8631 and 3045-1

EAGLE Libraries/HyTechDevices.lbr
=> fixed crystal restricts to conform with DRC

ULP Files/jlcpcb_smta_exporter_v7.ulp
=> added ULP to autogen JLC compliant BOM and pick and place files

EAGLE Libraries/HyTechDevices.lbr
added two current limiting resistors for dash LEDs.
=> added 15 ohm 0603 and 22 ohm 0805

EAGLE Libraries/HyTechDevices.lbr, ULP Files/export-bom.ulp
=> New BOM ULP

ULP Files/export-bom.ulp
=> More fixes

EAGLE Libraries/HyTechDevices.lbr
Added:
- Buffer logic gate symbol (based on inverter symbol)
- Buffer logic gate device (SN74LVC1G34)
=> Added buffer logic gate (sn74lvc1g34)

EAGLE Libraries/HyTechDevices.lbr
Deleted a few lines to fix M3 Mounting Hole Heatsink in Devices
*All datasheets, information, and/or useful links should be included in the Description within EAGLE.*
=> fixed library

EAGLE Libraries/HyTechDevices.lbr
Made + - symbols seperate texts in rgbw led footprint
*All datasheets, information, and/or useful links should be included in the Description within EAGLE.*
=> fixed +- symbols

CAM Files/2 Layer.cam, CAM Files/4 Layer.cam, CAM Files/6 Layer.cam, EAGLE Libraries/HyTechDevices.lbr
=> CAM updates

CAM Files/2 Layer.cam, CAM Files/4 Layer.cam, CAM Files/6 Layer.cam, EAGLE Libraries/HyTechDevices.lbr
This reverts commit 9b86064b732ffbab5cd5c92b54257f7da5b61ee4.
***Follow HyTech's [Electrical Designs Rules Review Process](https://gtvault.sharepoint.com/:w:/r/sites/HyTechRacing2/Shared%20Documents/Electrical%20-%20All/HT06/Guidelines%20Rules%20and%20Procedures/Electrical%20Designs%20Rules%20Review%20Process.docx?d=w0277498dfb4b4b9fbfad0e5db8a187c8&csf=1&web=1&e=LDFCNz) to understand circuit design flow …
=> Revert "CAM updates (#103)"

EAGLE Libraries/HyTechDevices.lbr
- [ x] Did you fill out the above template?
- [xx ] Did you assign the right people for review (on the right)?
=> Fixed AVR connector MPN and DKPN

EAGLE Libraries/HyTechExternal.lbr
- Added 2 pin nanofit receptacle ordering component to external library
=> Nanofit 2 pin receptacle
